SELECT username
FROM all_users
WHERE username='QUINDIOFLIX';

CREATE USER quindioflix
IDENTIFIED BY quindioflix
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA UNLIMITED ON users;

GRANT CREATE SESSION TO quindioflix;
GRANT CREATE TABLE TO quindioflix;
GRANT CREATE VIEW TO quindioflix;
GRANT CREATE SEQUENCE TO quindioflix;
GRANT CREATE PROCEDURE TO quindioflix;
GRANT CREATE TRIGGER TO quindioflix;
GRANT UNLIMITED TABLESPACE TO quindioflix;


-- ROLES
CREATE ROLE ROL_ADMIN;
CREATE ROLE ROL_ANALISTA;
CREATE ROLE ROL_SOPORTE;
CREATE ROLE ROL_CONTENIDO;

-- USUARIOS OPERATIVOS
CREATE USER ADMIN_QF IDENTIFIED BY Admin123;
CREATE USER ANALISTA_QF IDENTIFIED BY Analista123;
CREATE USER SOPORTE_QF IDENTIFIED BY Soporte123;
CREATE USER CONTENIDO_QF IDENTIFIED BY Contenido123;

-- LOGIN
GRANT CREATE SESSION TO ADMIN_QF;
GRANT CREATE SESSION TO ANALISTA_QF;
GRANT CREATE SESSION TO SOPORTE_QF;
GRANT CREATE SESSION TO CONTENIDO_QF;

-- ASIGNAR ROLES
GRANT ROL_ADMIN TO ADMIN_QF;
GRANT ROL_ANALISTA TO ANALISTA_QF;
GRANT ROL_SOPORTE TO SOPORTE_QF;
GRANT ROL_CONTENIDO TO CONTENIDO_QF;

-- VERIFICAR CREACIÓN
SELECT role
FROM dba_roles
WHERE role LIKE 'ROL_%'
ORDER BY role;

SELECT grantee, granted_role
FROM dba_role_privs
WHERE grantee IN ('ADMIN_QF','ANALISTA_QF','SOPORTE_QF','CONTENIDO_QF')
ORDER BY grantee;
